#include <stdio.h>

//30 Nombres
char h_name[30][30]={
"JOSE","JUAN","LUIS","MANUEL","ANTONIO","JESUS","CARLOS","FRANCISCO","ALBERTO","JORGE","MIGUEL",
"ANGEL","JAVIER","ALEJANDRO","ENRIQUE","VICTOR","ARTURO","CESAR","FERNANDO","PEDRO","MARTIN",
"ROBERTO","EDUARDO","MARIO","ARMANDO","SERGIO","RAUL","ALFREDO","RAFAEL","RICARDO"};

//30 Nombres
char m_name[30][30]={
"MARIA","GUADALUPE","ROSA","MARTHA","ANA","PATRICIA","LETICIA","ELENA","LAURA","ELIZABETH","ISABEL",
"ALICIA","MARGARITA","LUZ","ANGELICA","CLAUDIA","SILVIA","JUANA","GABRIELA","ADRIANA","VERONICA",
"TERESA","ALEJANDRA","ALMA","BEATRIZ","ARACELI","YOLANDA","BLANCA","SANDRA"};

char ap[50][30]={
"HERNANDEZ","GARCIA","MARTINEZ","LOPEZ","GONZALEZ","RODRIGUEZ","PEREZ","SANCHEZ","RAMIREZ","FLORES","CRUZ",
"GOMEZ","MORALES","VAZQUEZ","REYES","DIAZ","TORRES","GUTIERREZ","RUIZ","AGUILAR","MENDOZA","CASTILLO","ORTIZ",
"MORENO","RIVERA","RAMOS","ROMERO","JUAREZ","ALVAREZ","MENDEZ","CHAVEZ","HERRERA","MEDINA","DOMINGUEZ",
"CASTRO","GUZMAN","VARGAS","VELAZQUEZ","SALAZAR","ROJAS","ORTEGA","CORTES","SANTIAGO","GUERRERO","CONTRERAS",
"BAUTISTA","ESTRADA","LUNA","LARA","VASQUEZ"};


